### ISSUE TITLE
Possibly remove `unix-weak-link` feature

### ISSUE THREAD

**Issue by cpick** [novafacing/qemu-rs#27]
I was testing `qemu-plugin` on macOS (aarch64-apple-darwin) and having some trouble getting the examples running.  The issue turned out to be with the `unix-weak-link` feature that the examples enable.  (Debug builds would link, but release builds would fail with lots of undefined symbols.  Even then, the debug build wouldn't actually execute the plugin code when loaded via `qemu-system-x86_64 -plugin target/debug/*.dylib`.)

As I was debugging/thinking about that issue, I started to believe that using weak linking as done with that feature in "qemu-plugin/src/unix_weak_link/mod.rs" is probably not the "right" way to prevent the cdylib builds from failing due to undefined symbols.  On one hand it's not portable (as seen with the macOS issues), and on the other it can accidentally hide errors (a symbol that isn't actually in qemu, for example due to a typo, will silently use the weakly-linked copy).

I think the more standard solution is to tell the linker to allow undefined symbols in the cdylib.  That would allow the  `unix-weak-link` feature and its `unix_weak_link` module to be deleted altogether and any actually-missing symbols would cause `dlopen()` to fail when qemu tries to load the plugin (instead of silently using the weakly-linked copy's dummy implementation).

This can be done with the following linker options in ".cargo/config.toml":
```toml
[target.'cfg(target_os = "macos")']
rustflags = ["-Clink-arg=-undefined", "-Clink-arg=dynamic_lookup"]

[target.'cfg(all(target_family = "unix", not(target_os = "macos")))']
rustflags = ["-C", "link-args=-Wl,-z,undefs"]
```
